site_name: Vestibulandos
repo_name: 'Repositório de ArqDsw - Vestibulandos'
repo_url: 'https://github.com/UnBArqDsw/2020.1_G4_Vestibulandos'
theme:
    name: 'material'

nav:
    - Home: index.md
    - Base:
        - Design Sprint: 'base/design_sprint.md'
        - Metodologia: 'base/metodologia.md'
        - Plano de Análise de Riscos: 'base/plano_de_risco.md'
        - Pré-Rastreabilidade: 
            - RichPicture: 'base/pre_rastreabilidade/rich_picture.md'
            - 5W2H: 'base/pre_rastreabilidade/5W2H.md'
            - Mapa Mental: 'base/pre_rastreabilidade/mapa_mental.md'
        - Elicitação de requisitos : 
            - Brainstorm: 'base/elicitacao/brainstorming.md'
            - Entrevista: 'base/elicitacao/entrevista.md'
            - Introspecção: 'base/elicitacao/introspeccao.md'
            - Storyboard: 'base/elicitacao/storyboard.md'
            - Requisitos Elicitados: 'base/elicitacao/requisitos_elicitados.md'
        - Iniciativas Extras: 
            - Identidade visual: 'base/iniciativas_extras/id_visual.md'
            - Protótipos: 'base/iniciativas_extras/prototipos.md'
    - Modelagem: 
        - Diagramas Estáticos:
            - Diagrama de Classes: 'modelagem/diagrama_de_classe.md'
            - Diagrama de Pacotes: '/modelagem/diagrama_de_pacotes.md'
        - Diagramas Dinâmicos:
            - Diagrama de Comunicação: 'modelagem/diagrama_de_comunicacao.md'
            - Diagrama de Estados: 'modelagem/diagrama_de_estados.md'
        - Lexico: 'modelagem/lexico.md'
        - Iniciativas: 'modelagem/iniciativas_extras.md'
    
    
