site_name: Vestibulandos
repo_name: 'Repositório de ArqDsw - Vestibulandos'
repo_url: 'https://github.com/UnBArqDsw/2020.1_G4_Vestibulandos'
theme:
    name: 'material'

nav:
    - Home: index.md
    - Base:
        - Design Sprint: 'base/design_sprint.md'
        - Metodologia: 'base/metodologia.md'
        - Plano de Análise de Riscos: 'base/plano_de_risco.md'
        - Pré-Rastreabilidade: 
            - RichPicture: 'base/pre_rastreabilidade/rich_picture.md'
            - 5W2H: 'base/pre_rastreabilidade/5W2H.md'
            - Mapa Mental: 'base/pre_rastreabilidade/mapa_mental.md'
            - Protótipos: 'base/pre_rastreabilidade/prototipos.md'
        - Elicitação de requisitos : 
            - Brainstorm: 'base/elicitacao/brainstorming.md'
            - Entrevista: 'base/elicitacao/entrevista.md'
            - Introspecção: 'base/elicitacao/introspeccao.md'
            - Storyboard: 'base/elicitacao/storyboard.md'
            - Requisitos Elicitados: 'base/elicitacao/requisitos_elicitados.md'
        - Priorização de requisitos:
            - MoSCoW: 'base/priorizacao/moscow.md'
            - First Things First: 'base/priorizacao/first_things_first.md'
        - Iniciativas Extras: 
            - Identidade visual: 'base/iniciativas_extras/id_visual.md'
    - Modelagem:
        - Backlog: 'modelagem/backlog.md'
        - Diagramas Estáticos:
            - Diagrama de Classes: 'modelagem/diagramas_estaticos/diagrama_de_classe.md'
            - Diagrama de Componentes: 'modelagem/diagramas_estaticos/diagrama_de_componentes.md'
            - Diagrama de Pacotes: 'modelagem/diagramas_estaticos/diagrama_de_pacotes.md'
        - Diagramas Dinâmicos:
            - Diagrama de Atividades: 'modelagem/diagramas_dinamicos/diagrama_de_atividades.md'
            - Diagrama de Comunicação: 'modelagem/diagramas_dinamicos/diagrama_de_comunicacao.md'
            - Diagrama de Estados: 'modelagem/diagramas_dinamicos/diagrama_de_estados.md'
            - Diagrama de Sequencia: 'modelagem/diagramas_dinamicos/diagrama_de_sequencia.md'
        - Lexico: 'modelagem/lexico.md'
        - Iniciativas Extras: 
            - Registro de Iniciativas Extras: 'modelagem/iniciativas_extras.md'
            - Especificação Suplementar: 'base/iniciativas_extras/especificacao_suplementar.md'
    - Padrões de Projeto:
        - GRASP: 'padroes_de_projeto/grasps.md'
        - GOFs Criacionais: 'padroes_de_projeto/gofs_criacionais.md'
        - GOFs Estruturais: 'padroes_de_projeto/gofs_estruturais.md'
        - GOFs Comportamentais: 'padroes_de_projeto/gofs_comportamentais.md'
        
    - Reuniões:
        - Ata 1: 'reunioes/ata_1.md'
        - Ata 2: 'reunioes/ata_2.md'
        - Ata 3: 'reunioes/ata_3.md'
        - Ata 4: 'reunioes/ata_4.md'
        - Ata 5: 'reunioes/ata_5.md'
        - Ata 6: 'reunioes/ata_6.md'
        - Ata 7: 'reunioes/ata_7.md'
        - Ata 8: 'reunioes/ata_8.md'
        - Ata 9: 'reunioes/ata_9.md'
    
    
