site_name: Vestibulandos
repo_name: 'Repositório de ArqDsw - Vestibulandos'
repo_url: 'https://github.com/UnBArqDsw/2020.1_G4_Vestibulandos'
theme:
    name: 'material'

nav:
    - Home: index.md
    - Design Sprint: design_sprint.md
    - Metodologia: metodologia.md
    - Pré-Rastreabilidade: 
      - RichPicture: rich_picture.md
      - 5W2H: 5W2H.md
    - Elicitação de requisitos : 
        - Brainstorm: brainstorming.md
        - Entrevista: entrevista.md
        - Introspecção: introspeccao.md
        - Lexico: lexico.md
        - Mapa Mental: mapa_mental.md
        - Storyboard: storyboard.md
        - Requisitos Elicitados: requisitos_elicitados.md
    - Plano de Análise de Riscos: plano_de_analise.md
    - Modelagem: 
        - Diagramas Estáticos:
            - Diagrama de Classes: diagrama_de_classe.md
    - Iniciativas Extras: 
        - Identidade visual: id_visual.md
        - Protótipos: prototipos.md
    

      