site_name: Vestibulandos
repo_name: 'Repositório de ArqDsw - Vestibulandos'
repo_url: 'https://github.com/UnBArqDsw/2020.1_G4_Vestibulandos'
theme:
    name: 'material'

nav:
    - Home: index.md
    - Planejamento: planejamento.md
    - Pré-Rastreabilidade: 
      - RichPicture: richPicture.md
      - 5W2H: 5W2H.md
    - Elicitação de requisitos : 
        - Requisitos ELicitados: requisitos_elicitados.md