site_name: Vestibulandos
repo_name: 'Repositório de ArqDsw - Vestibulandos'
repo_url: 'https://github.com/UnBArqDsw/2020.1_G4_Vestibulandos'
theme:
    name: 'material'

nav:
    - Home: index.md
    - Design Sprint: design_sprint.md
    - Pré-Rastreabilidade: 
      - RichPicture: rich_picture.md
      - 5W2H: 5W2H.md
    - Elicitação de requisitos : 
        - Brainstorm: brainstorm.md
        - Entrevista: entrevista.md
        - Introspecção: introspeccao.md
    - Iniciativas Extras: 
        - Identidade visual: id_visual.md
    - Plano de Análise de Riscos: plano_de_analise.md

      